//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discharge
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int OpId { get; set; }
    
        public virtual Op_Table Op_Table { get; set; }
    }
}
